# Generated by Django 2.0.4 on 2018-04-18 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_title',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='tags',
            old_name='tags_title',
            new_name='tags',
        ),
    ]
